# These are supported funding model platforms

bdnaturetech: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]

bdnaturetech: # Replace with a single Buy Me a Coffee username
https://bdnaturetech.com/: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
